package com.info.entity;

public class CourseUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_user_info.id
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_user_info.uId
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_user_info.cId
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    private Integer cId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_user_info.id
     *
     * @return the value of course_user_info.id
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_user_info.id
     *
     * @param id the value for course_user_info.id
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_user_info.uId
     *
     * @return the value of course_user_info.uId
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_user_info.uId
     *
     * @param uId the value for course_user_info.uId
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_user_info.cId
     *
     * @return the value of course_user_info.cId
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_user_info.cId
     *
     * @param cId the value for course_user_info.cId
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }
}