package com.info.entity;

public class CourseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.id
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.cName
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.cAddress
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    private String cAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.id
     *
     * @return the value of course_info.id
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.id
     *
     * @param id the value for course_info.id
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.cName
     *
     * @return the value of course_info.cName
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.cName
     *
     * @param cName the value for course_info.cName
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public void setcName(String cName) {
        this.cName = cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.cAddress
     *
     * @return the value of course_info.cAddress
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.cAddress
     *
     * @param cAddress the value for course_info.cAddress
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress;
    }
}