package com.info.entity;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.uName
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.uNumber
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    private Integer uNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.uName
     *
     * @return the value of user_info.uName
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.uName
     *
     * @param uName the value for user_info.uName
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.uNumber
     *
     * @return the value of user_info.uNumber
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public Integer getuNumber() {
        return uNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.uNumber
     *
     * @param uNumber the value for user_info.uNumber
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    public void setuNumber(Integer uNumber) {
        this.uNumber = uNumber;
    }
}