package com.info.mapper;

import com.info.entity.CourseUserInfo;

public interface CourseUserInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    int insert(CourseUserInfo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    CourseUserInfo selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    int updateByPrimaryKey(CourseUserInfo record);
}