package com.info.mapper;

import com.info.entity.CourseInfo;

public interface CourseInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    int insert(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    int insertSelective(CourseInfo record);

}