package com.info.mapper;

import java.util.List;

import com.info.entity.UserInfo;

public interface UserInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    UserInfo deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    UserInfo selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Jan 13 14:59:31 CST 2016
     */
    int updateByPrimaryKey(UserInfo record);
    
    List<UserInfo> queryAll();
    
    
}